"use strict";

const ROLES = require("../constants/roles");

const RESOURCES = {
  venues: {
    table: "venues",
    label: "Venue",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: [
      "name",
      "slug",
      "address",
      "city",
      "country",
      "capacity",
      "image_url",
      "map_url",
      "latitude",
      "longitude",
      "status",
    ],
    searchable: ["name", "address", "city", "country"],
    softDelete: true,
    defaultSort: "created_at",
  },
  categories: {
    table: "event_categories",
    label: "Category",
    roles: [ROLES.ADMIN],
    columns: ["name", "slug", "description", "icon", "sort_order", "is_active"],
    searchable: ["name", "slug", "description"],
    defaultSort: "sort_order",
  },
  organizers: {
    table: "organizers",
    label: "Organizer",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: [
      "user_id",
      "organization_name",
      "slug",
      "description",
      "logo_url",
      "website",
      "is_verified",
      "is_active",
    ],
    searchable: ["organization_name", "slug", "website"],
    softDelete: true,
    defaultSort: "created_at",
    organizerCondition: (idx) => `r.user_id = $${idx}`,
  },
  "event-images": {
    table: "event_images",
    label: "Event Image",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: ["event_id", "url", "alt_text", "sort_order", "is_cover"],
    searchable: ["url", "alt_text"],
    defaultSort: "sort_order",
    organizerCondition: (idx) =>
      `EXISTS (SELECT 1 FROM events e WHERE e.id = r.event_id AND e.organizer_id IN (SELECT id FROM organizers WHERE user_id = $${idx} AND deleted_at IS NULL))`,
  },
  "ticket-types": {
    table: "ticket_types",
    label: "Ticket Type",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: [
      "event_id",
      "name",
      "description",
      "price",
      "currency",
      "quantity",
      "quantity_sold",
      "max_per_order",
      "sale_starts_at",
      "sale_ends_at",
      "is_active",
      "sort_order",
    ],
    searchable: ["name", "description", "currency"],
    defaultSort: "sort_order",
    organizerCondition: (idx) =>
      `EXISTS (SELECT 1 FROM events e WHERE e.id = r.event_id AND e.organizer_id IN (SELECT id FROM organizers WHERE user_id = $${idx} AND deleted_at IS NULL))`,
  },
  coupons: {
    table: "coupons",
    label: "Coupon",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: [
      "code",
      "discount_type",
      "discount_value",
      "usage_limit",
      "used_count",
      "starts_at",
      "expires_at",
      "event_id",
      "is_active",
      "created_by",
    ],
    searchable: ["code", "discount_type"],
    defaultSort: "created_at",
    organizerCondition: (idx) =>
      `(r.created_by = $${idx} OR EXISTS (SELECT 1 FROM events e WHERE e.id = r.event_id AND e.organizer_id IN (SELECT id FROM organizers WHERE user_id = $${idx} AND deleted_at IS NULL)))`,
  },
  "seat-maps": {
    table: "seat_maps",
    label: "Seat Map",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: ["venue_id", "name", "rows", "seats_per_row", "map_config"],
    searchable: ["name"],
    defaultSort: "created_at",
  },
  seats: {
    table: "seats",
    label: "Seat",
    roles: [ROLES.ADMIN, ROLES.ORGANIZER],
    columns: [
      "seat_map_id",
      "row_label",
      "seat_number",
      "section",
      "category",
      "status",
      "is_blocked",
    ],
    searchable: ["row_label", "section", "category", "status"],
    defaultSort: "row_label",
  },
  "audit-logs": {
    table: "audit_logs",
    label: "Audit Log",
    roles: [ROLES.ADMIN],
    columns: [
      "actor_id",
      "actor_ip",
      "action",
      "resource_type",
      "resource_id",
      "old_values",
      "new_values",
    ],
    searchable: ["action", "resource_type"],
    readOnly: true,
    defaultSort: "created_at",
  },
};

const getResource = (name) => RESOURCES[name] || null;

module.exports = { RESOURCES, getResource };
